name: "Use NPM Token"
description: "Use an NPM token within an .npmrc file inside GitHub actions. Scoped packages are the primary use case."
author: "Derek Kershner"
inputs:
  token:
    description: "An NPM token with whatever access is needed for your GitHub Action workflow "
    required: true
  workspace:
    description: The location of your Node workspace (needs to be a sibling of package.json)
    default: ./
    required: false

runs:
  using: "node12"
  main: "dist/index.js"
